<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="0" total="5" passed="1">
  <reporter-output>
    <line>
      <![CDATA[About to begin executing Suite Suite usa black caviar]]>
    </line>
    <line>
      <![CDATA[
 ========About to begin executing Test TestLogin========= 
]]>
    </line>
    <line>
      <![CDATA[Test Method resides in accountManagement.TestLoginFunctionality]]>
    </line>
    <line>
      <![CDATA[Test Method had the following parameters : ]]>
    </line>
    <line>
      <![CDATA[Test Method had the following parameters : [Ljava.lang.Object;@6c345c5f]]>
    </line>
    <line>
      <![CDATA[Test Status: Pass]]>
    </line>
    <line>
      <![CDATA[Retrying test LoginToStore with status FAILURE for the 1 time(s).]]>
    </line>
    <line>
      <![CDATA[Test is skipped:LoginToStore]]>
    </line>
    <line>
      <![CDATA[Retrying test LoginToStore with status FAILURE for the 2 time(s).]]>
    </line>
    <line>
      <![CDATA[Test is skipped:LoginToStore]]>
    </line>
    <line>
      <![CDATA[Retrying test LoginToStore with status FAILURE for the 3 time(s).]]>
    </line>
    <line>
      <![CDATA[Test is skipped:LoginToStore]]>
    </line>
    <line>
      <![CDATA[<a href='C:\Users\vk\git\opencart_pom\opencart\test-output\pom_framework_output\screenshots\failed_tests\LoginToStore_26_09_2019_11_43_48.png'> <img src='C:\Users\vk\git\opencart_pom\opencart\test-output\pom_framework_output\screenshots\failed_tests\LoginToStore_26_09_2019_11_43_48.png' height='100' width='100'/> </a>]]>
    </line>
    <line>
      <![CDATA[Test Method resides in accountManagement.TestLoginFunctionality]]>
    </line>
    <line>
      <![CDATA[Test Method had the following parameters : ]]>
    </line>
    <line>
      <![CDATA[Test Method had the following parameters : [Ljava.lang.Object;@66434cc8]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[<a href='C:\Users\vk\git\opencart_pom\opencart\test-output\pom_framework_output\screenshots\blank_26_09_2019_11_43_48.png'> <img src='C:\Users\vk\git\opencart_pom\opencart\test-output\pom_framework_output\screenshots\blank_26_09_2019_11_43_48.png' height='100' width='100'/> </a>]]>
    </line>
  </reporter-output>
  <suite name="Suite usa black caviar" duration-ms="21140" started-at="2019-09-26T15:43:29Z" finished-at="2019-09-26T15:43:50Z">
    <groups>
    </groups>
    <test name="TestLogin" duration-ms="21140" started-at="2019-09-26T15:43:29Z" finished-at="2019-09-26T15:43:50Z">
      <class name="accountManagement.TestLoginFunctionality">
        <test-method status="PASS" signature="setUp(java.lang.String, java.lang.String)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121]" name="setUp" is-config="true" duration-ms="5472" started-at="2019-09-26T15:43:29Z" finished-at="2019-09-26T15:43:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[stg]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121]" name="beforeMethod" is-config="true" duration-ms="5" started-at="2019-09-26T15:43:35Z" finished-at="2019-09-26T15:43:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void accountManagement.TestLoginFunctionality.LoginToStore(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="LoginToStore(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121]" name="LoginToStore" duration-ms="4234" started-at="2019-09-26T15:43:35Z" data-provider="getCSVData" finished-at="2019-09-26T15:43:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC_001]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[kvalera29@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Y]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Test Method resides in accountManagement.TestLoginFunctionality]]>
            </line>
            <line>
              <![CDATA[Test Method had the following parameters : ]]>
            </line>
            <line>
              <![CDATA[Test Method had the following parameters : [Ljava.lang.Object;@6c345c5f]]>
            </line>
            <line>
              <![CDATA[Test Status: Pass]]>
            </line>
          </reporter-output>
        </test-method> <!-- LoginToStore -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121]" name="afterMethod" is-config="true" duration-ms="1" started-at="2019-09-26T15:43:39Z" finished-at="2019-09-26T15:43:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LoginToStore status=SUCCESS method=TestLoginFunctionality.LoginToStore(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121] output=Test Method resides in accountManagement.TestLoginFunctionality]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-09-26T15:43:39Z" finished-at="2019-09-26T15:43:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void accountManagement.TestLoginFunctionality.LoginToStore(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="LoginToStore(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121]" name="LoginToStore" duration-ms="2131" started-at="2019-09-26T15:43:39Z" data-provider="getCSVData" finished-at="2019-09-26T15:43:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC_002]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test@test.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Y]]>
              </value>
            </param>
          </params>
          <exception class="org.junit.ComparisonFailure">
            <message>
              <![CDATA[expected:<[Account Login]> but was:<[My Account]>]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.junit.ComparisonFailure: expected:<[Account Login]> but was:<[My Account]>
at org.junit.Assert.assertEquals(Assert.java:125)
at org.junit.Assert.assertEquals(Assert.java:147)
at accountManagement.TestLoginFunctionality.LoginToStore(TestLoginFunctionality.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
]]>
            </full-stacktrace>
          </exception> <!-- org.junit.ComparisonFailure -->
          <reporter-output>
            <line>
              <![CDATA[Retrying test LoginToStore with status FAILURE for the 1 time(s).]]>
            </line>
            <line>
              <![CDATA[Test is skipped:LoginToStore]]>
            </line>
          </reporter-output>
        </test-method> <!-- LoginToStore -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121]" name="afterMethod" is-config="true" duration-ms="1" started-at="2019-09-26T15:43:41Z" finished-at="2019-09-26T15:43:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LoginToStore status=SKIP method=TestLoginFunctionality.LoginToStore(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121] output=Retrying test LoginToStore with status FAILURE for the 1 time(s).]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-09-26T15:43:41Z" finished-at="2019-09-26T15:43:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void accountManagement.TestLoginFunctionality.LoginToStore(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="LoginToStore(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121]" name="LoginToStore" duration-ms="2182" started-at="2019-09-26T15:43:41Z" data-provider="getCSVData" finished-at="2019-09-26T15:43:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC_002]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test@test.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Y]]>
              </value>
            </param>
          </params>
          <exception class="org.junit.ComparisonFailure">
            <message>
              <![CDATA[expected:<[Account Login]> but was:<[My Account]>]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.junit.ComparisonFailure: expected:<[Account Login]> but was:<[My Account]>
at org.junit.Assert.assertEquals(Assert.java:125)
at org.junit.Assert.assertEquals(Assert.java:147)
at accountManagement.TestLoginFunctionality.LoginToStore(TestLoginFunctionality.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
]]>
            </full-stacktrace>
          </exception> <!-- org.junit.ComparisonFailure -->
          <reporter-output>
            <line>
              <![CDATA[Retrying test LoginToStore with status FAILURE for the 2 time(s).]]>
            </line>
            <line>
              <![CDATA[Test is skipped:LoginToStore]]>
            </line>
          </reporter-output>
        </test-method> <!-- LoginToStore -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121]" name="afterMethod" is-config="true" duration-ms="1" started-at="2019-09-26T15:43:43Z" finished-at="2019-09-26T15:43:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LoginToStore status=SKIP method=TestLoginFunctionality.LoginToStore(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121] output=Retrying test LoginToStore with status FAILURE for the 2 time(s).]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-09-26T15:43:43Z" finished-at="2019-09-26T15:43:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void accountManagement.TestLoginFunctionality.LoginToStore(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="LoginToStore(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121]" name="LoginToStore" duration-ms="2309" started-at="2019-09-26T15:43:43Z" data-provider="getCSVData" finished-at="2019-09-26T15:43:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC_002]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test@test.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Y]]>
              </value>
            </param>
          </params>
          <exception class="org.junit.ComparisonFailure">
            <message>
              <![CDATA[expected:<[Account Login]> but was:<[My Account]>]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.junit.ComparisonFailure: expected:<[Account Login]> but was:<[My Account]>
at org.junit.Assert.assertEquals(Assert.java:125)
at org.junit.Assert.assertEquals(Assert.java:147)
at accountManagement.TestLoginFunctionality.LoginToStore(TestLoginFunctionality.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
]]>
            </full-stacktrace>
          </exception> <!-- org.junit.ComparisonFailure -->
          <reporter-output>
            <line>
              <![CDATA[Retrying test LoginToStore with status FAILURE for the 3 time(s).]]>
            </line>
            <line>
              <![CDATA[Test is skipped:LoginToStore]]>
            </line>
          </reporter-output>
        </test-method> <!-- LoginToStore -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121]" name="afterMethod" is-config="true" duration-ms="1" started-at="2019-09-26T15:43:46Z" finished-at="2019-09-26T15:43:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LoginToStore status=SKIP method=TestLoginFunctionality.LoginToStore(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121] output=Retrying test LoginToStore with status FAILURE for the 3 time(s).]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-09-26T15:43:46Z" finished-at="2019-09-26T15:43:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void accountManagement.TestLoginFunctionality.LoginToStore(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="LoginToStore(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121]" name="LoginToStore" duration-ms="2503" started-at="2019-09-26T15:43:46Z" data-provider="getCSVData" finished-at="2019-09-26T15:43:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC_002]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test@test.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Y]]>
              </value>
            </param>
          </params>
          <exception class="org.junit.ComparisonFailure">
            <message>
              <![CDATA[expected:<[Account Login]> but was:<[My Account]>]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.junit.ComparisonFailure: expected:<[Account Login]> but was:<[My Account]>
at org.junit.Assert.assertEquals(Assert.java:125)
at org.junit.Assert.assertEquals(Assert.java:147)
at accountManagement.TestLoginFunctionality.LoginToStore(TestLoginFunctionality.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
]]>
            </full-stacktrace>
          </exception> <!-- org.junit.ComparisonFailure -->
          <reporter-output>
            <line>
              <![CDATA[<a href='C:\Users\vk\git\opencart_pom\opencart\test-output\pom_framework_output\screenshots\failed_tests\LoginToStore_26_09_2019_11_43_48.png'> <img src='C:\Users\vk\git\opencart_pom\opencart\test-output\pom_framework_output\screenshots\failed_tests\LoginToStore_26_09_2019_11_43_48.png' height='100' width='100'/> </a>]]>
            </line>
            <line>
              <![CDATA[Test Method resides in accountManagement.TestLoginFunctionality]]>
            </line>
            <line>
              <![CDATA[Test Method had the following parameters : ]]>
            </line>
            <line>
              <![CDATA[Test Method had the following parameters : [Ljava.lang.Object;@66434cc8]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- LoginToStore -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121]" name="afterMethod" is-config="true" duration-ms="326" started-at="2019-09-26T15:43:48Z" finished-at="2019-09-26T15:43:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LoginToStore status=FAILURE method=TestLoginFunctionality.LoginToStore(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121] output=<a href='C:\Users\vk\git\opencart_pom\opencart\test-output\pom_framework_output\screenshots\failed_tests\LoginToStore_26_09_2019_11_43_48.png'> <img src='C:\Users\vk\git\opencart_pom\opencart\test-output\pom_framework_output\screenshots\failed_tests\LoginToStore_26_09_2019_11_43_48.png' height='100' width='100'/> </a>]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[<a href='C:\Users\vk\git\opencart_pom\opencart\test-output\pom_framework_output\screenshots\blank_26_09_2019_11_43_48.png'> <img src='C:\Users\vk\git\opencart_pom\opencart\test-output\pom_framework_output\screenshots\blank_26_09_2019_11_43_48.png' height='100' width='100'/> </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121]" name="afterClass" is-config="true" duration-ms="1305" started-at="2019-09-26T15:43:49Z" finished-at="2019-09-26T15:43:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterTest(org.testng.ITestContext)[pri:0, instance:accountManagement.TestLoginFunctionality@2de23121]" name="afterTest" is-config="true" duration-ms="198" started-at="2019-09-26T15:43:50Z" finished-at="2019-09-26T15:43:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@7cab1508]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- accountManagement.TestLoginFunctionality -->
    </test> <!-- TestLogin -->
  </suite> <!-- Suite usa black caviar -->
</testng-results>
